version: '3'
services:
  web:
    build: .
    ports:
      - "8000:5000"
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TZ=Asia/Shanghai  # 设置时区
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Shanghai  # 设置时区
