version: '3.7'
services:
  web:
    image: xiebaiyuan/flask-app:0.2
    platform: linux/amd64
    ports:
      - "8000:5000"
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    platform: linux/amd64
    ports:
      - "6379:6379"